# Generated by OmopViewer 0.7.0
# Be careful editing this file

library(bslib)
library(CohortCharacteristics)
library(CohortSurvival)
library(DiagrammeR)
library(DiagrammeRsvg)
library(dplyr)
library(DT)
library(ggplot2)
library(gt)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(rlang)
library(rsvg)
library(shiny)
library(shinycssloaders)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "studyData.RData")
resultFiles <- list.files(
  c(file.path(getwd(), "rawData"), file.path(getwd(), "data")),
  pattern = "[.]csv$",
  full.names = TRUE
)
if (
  !file.exists(fileData) ||
    (length(resultFiles) > 0 &&
      max(file.info(resultFiles)$mtime) > file.info(fileData)$mtime)
) {
  source(file.path(getwd(), "rawData", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "rawData"))

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))
